### ISSUE TITLE
Setup Yocto repository for baseline Kirkstone build with meta-tegra

### ISSUE THREAD

**Issue by DomenicP** [DomenicP/final-project-assignment-DomenicP#1]
## Description

Fork https://github.com/OE4T/tegra-demo-distro/tree/kirkstone-l4t-r32.7.x as a starting point and successfully deploy a base image to the Jetson Nano

May need to perform minimal configuration (SD card size, static IP address, etc.)

## Definition of Done (DoD)

- [x] Yocto repository can successfully build a base image for the Jetson Nano
- [x] Base image can be flashed onto Jetson Nano
- [x] Jetson Nano boots and can be remotely accessed over SSH to confirm successful flashing

## Blockers

- [x] SD card flashing is taking longer than anticipated, created #4 for follow-up

**Comment by DomenicP** [comment]
Successful build output for base image:

```shell
$ make build
. setup-env && bitbake demo-image-base
### Shell environment set up for builds. ###

You can now run 'bitbake <target>'
Targets for building Tegra demo images with test applications:
    core-image-minimal  - minimally bootable image (no demo apps, no graphics)
    demo-image-base     - basic image with no graphics
    demo-image-egl      - basic image with DRM/EGL, no window manager
    demo-image-sato     - X11 image with 'sato' UI
    demo-image-weston   - Wayland with Weston compositor
    demo-image-full     - X11/sato UI plus docker, openCV, VPI, TensorRT and multimedia API samples

-e Layers differ from /home/domenic/src/final-project-DomenicP/layers/meta-tegrademo/conf/template-tegrademo-mender/bblayers.conf.sample:
-e --- -        2024-11-25 13:33:49.196112934 -0500
+++ /home/domenic/src/final-project-DomenicP/build/conf/bblayers.conf   2024-11-24 18:29:07.497385689 -0500
@@ -21,4 +21,5 @@
   /home/domenic/src/final-project-DomenicP/layers/meta-tegra-support \
   /home/domenic/src/final-project-DomenicP/layers/meta-demo-ci \
   /home/domenic/src/final-project-DomenicP/layers/meta-tegrademo \
+  /home/domenic/src/final-project-DomenicP/layers/meta-aesd \
   "
Loading cache: 100% |                                                                                                                                                       | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |######################################################################################################################################################| Time: 0:00:53
Parsing of 2864 .bb files complete (0 cached, 2864 parsed). 4389 targets, 126 skipped, 2 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "2.0.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-oe4t-linux"
MACHINE              = "jetson-nano-devkit"
DISTRO               = "tegrademo-mender"
DISTRO_VERSION       = "4.0.23+snapshot"
TUNE_FEATURES        = "aarch64 armv8a crc"
TARGET_FPU           = ""
meta                 = "kirkstone:8e092852b63e998d990b8f8e1aa91297dec4430f"
meta-tegra
contrib              = "kirkstone-l4t-r32.7.x:928ba1b5fd3a49c511a29fe2e00de971675e42d5"
meta-oe
meta-python
meta-networking
meta-filesystems     = "kirkstone:4ad41baed6236d499804cbfc4f174042d84fce97"
meta-virtualization  = "kirkstone:c996df33763f292da5e7513c574272d7de23eafc"
meta-tegra-community = "kirkstone-l4t-r32.7.x:8f2e68383378f8a57437e4832f6b6de5be139b2b"
meta-mender-core     = "kirkstone:9efa9409684e303472ed9dae749ab663909eb689"
meta-mender-tegra-jetpack4 = "kirkstone:1068f3427a9c6956cefca2f920ce29ed52256dee"
meta-tegra-support
meta-demo-ci
meta-tegrademo
meta-aesd            = "yocto-repository-setup:0cb953d7eb401a3d3d1340e9214589e996320ecb"

Initialising tasks: 100% |###################################################################################################################################################| Time: 0:00:03
Sstate summary: Wanted 78 Local 65 Mirrors 0 Missed 13 Current 1984 (83% match, 99% complete)
Removing 13 stale sstate objects for arch jetson_nano_devkit: 100% |#########################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 4988 tasks of which 4964 didn't need to be rerun and all succeeded.
```

Build output folder

```bash
$ ls build/links/deploy/ | grep demo-image-base
demo-image-base-jetson-nano-devkit-20241125183444.bootstrap-artifact
demo-image-base-jetson-nano-devkit-20241125183444.dataimg
demo-image-base-jetson-nano-devkit-20241125183444.ext4
demo-image-base-jetson-nano-devkit-20241125183444.manifest
demo-image-base-jetson-nano-devkit-20241125183444.mender
demo-image-base-jetson-nano-devkit-20241125183444.tegraflash.tar.gz
demo-image-base-jetson-nano-devkit-20241125183444.testdata.json
demo-image-base-jetson-nano-devkit.bootstrap-artifact
demo-image-base-jetson-nano-devkit.dataimg
demo-image-base-jetson-nano-devkit.ext4
demo-image-base-jetson-nano-devkit.manifest
demo-image-base-jetson-nano-devkit.mender
demo-image-base-jetson-nano-devkit.tegraflash.tar.gz
demo-image-base-jetson-nano-devkit.testdata.json
```

Note the `.tegraflash.tar.gz` for initial SD card flashing and the `.mender` for future SW updates.

**Comment by DomenicP** [comment]
SSH login:

```bash
$ cat ~/.ssh/config
Host jetson-dev
    Hostname 10.1.0.64
    User root
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

$ ssh jetson-dev
Warning: Permanently added '10.1.0.64' (ECDSA) to the list of known hosts.
Last login: Mon Nov 25 20:06:54 2024 from 10.1.0.5
root@jetson-nano-devkit:~# cat /etc/os-release
ID=tegrademo-mender
NAME="OE4Tegra Demonstration Distro with Mender"
VERSION="4.0.23-31b5695-dirty-domenic"
VERSION_ID="4.0.23-31b5695-dirty-domenic"
PRETTY_NAME="OE4Tegra Demonstration Distro with Mender 4.0.23-31b5695-dirty-domenic"
DISTRO_CODENAME="kirkstone-l4t-r32.7"
root@jetson-nano-devkit:~# uname -a
Linux jetson-nano-devkit 4.9.337-l4t-r32.7.5+ga8ca89dd604a #1 SMP PREEMPT Sat Jun 29 15:06:59 UTC 2024 aarch64 GNU/Linux
```
